export const reportInitialDetailsSchema = {
  title: 'report_initial_details schema',
  version: 0,
  description: 'report_initial_details table',
  primaryKey: 'id',
  type: 'object',
  properties: {
    id: { type: 'string', maxLength: 36 },
    report_id: { type: 'string' },
    hospital_number: { type: 'string' },
    histology_number: { type: 'string' },
    referring_hospital: { type: 'string' },
    referring_clinician: { type: 'string' },
    reporting_date: { type: 'string', format: 'date' },
    side: { type: 'string' },
    date_typed: { type: 'string', format: 'date' },
    typed_by: { type: 'string' },
  },
  required: [
    'id',
    'report_id',
    'hospital_number',
    'histology_number',
    'referring_hospital',
    'referring_clinician',
    'reporting_date',
    'side',
    'date_typed',
    'typed_by',
  ],
};
